org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.251
neo_version_range=[21.1.235,)
loader_version_range=[1,)

mod_id=omnira
mod_name=Omnira
mod_license=MIT
mod_version=0.5.1
mod_group_id=com.mcmagic.omnira
